// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: impression_tracking.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ImpressionTrackerService_TrackImpression_FullMethodName = "/arago.ImpressionTrackerService/TrackImpression"
)

// ImpressionTrackerServiceClient is the client API for ImpressionTrackerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImpressionTrackerServiceClient interface {
	TrackImpression(ctx context.Context, in *TrackImpressionRequest, opts ...grpc.CallOption) (*TrackImpressionResponse, error)
}

type impressionTrackerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImpressionTrackerServiceClient(cc grpc.ClientConnInterface) ImpressionTrackerServiceClient {
	return &impressionTrackerServiceClient{cc}
}

func (c *impressionTrackerServiceClient) TrackImpression(ctx context.Context, in *TrackImpressionRequest, opts ...grpc.CallOption) (*TrackImpressionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrackImpressionResponse)
	err := c.cc.Invoke(ctx, ImpressionTrackerService_TrackImpression_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImpressionTrackerServiceServer is the server API for ImpressionTrackerService service.
// All implementations must embed UnimplementedImpressionTrackerServiceServer
// for forward compatibility.
type ImpressionTrackerServiceServer interface {
	TrackImpression(context.Context, *TrackImpressionRequest) (*TrackImpressionResponse, error)
	mustEmbedUnimplementedImpressionTrackerServiceServer()
}

// UnimplementedImpressionTrackerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImpressionTrackerServiceServer struct{}

func (UnimplementedImpressionTrackerServiceServer) TrackImpression(context.Context, *TrackImpressionRequest) (*TrackImpressionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrackImpression not implemented")
}
func (UnimplementedImpressionTrackerServiceServer) mustEmbedUnimplementedImpressionTrackerServiceServer() {
}
func (UnimplementedImpressionTrackerServiceServer) testEmbeddedByValue() {}

// UnsafeImpressionTrackerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImpressionTrackerServiceServer will
// result in compilation errors.
type UnsafeImpressionTrackerServiceServer interface {
	mustEmbedUnimplementedImpressionTrackerServiceServer()
}

func RegisterImpressionTrackerServiceServer(s grpc.ServiceRegistrar, srv ImpressionTrackerServiceServer) {
	// If the following call pancis, it indicates UnimplementedImpressionTrackerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImpressionTrackerService_ServiceDesc, srv)
}

func _ImpressionTrackerService_TrackImpression_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackImpressionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpressionTrackerServiceServer).TrackImpression(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImpressionTrackerService_TrackImpression_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpressionTrackerServiceServer).TrackImpression(ctx, req.(*TrackImpressionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImpressionTrackerService_ServiceDesc is the grpc.ServiceDesc for ImpressionTrackerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImpressionTrackerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arago.ImpressionTrackerService",
	HandlerType: (*ImpressionTrackerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TrackImpression",
			Handler:    _ImpressionTrackerService_TrackImpression_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "impression_tracking.proto",
}
