// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: impression_tracking.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrackImpressionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdId          string                 `protobuf:"bytes,1,opt,name=ad_id,json=adId,proto3" json:"ad_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackImpressionRequest) Reset() {
	*x = TrackImpressionRequest{}
	mi := &file_impression_tracking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackImpressionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackImpressionRequest) ProtoMessage() {}

func (x *TrackImpressionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_impression_tracking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackImpressionRequest.ProtoReflect.Descriptor instead.
func (*TrackImpressionRequest) Descriptor() ([]byte, []int) {
	return file_impression_tracking_proto_rawDescGZIP(), []int{0}
}

func (x *TrackImpressionRequest) GetAdId() string {
	if x != nil {
		return x.AdId
	}
	return ""
}

type TrackImpressionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AdId             string                 `protobuf:"bytes,1,opt,name=ad_id,json=adId,proto3" json:"ad_id,omitempty"`
	TotalImpressions int64                  `protobuf:"varint,2,opt,name=total_impressions,json=totalImpressions,proto3" json:"total_impressions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TrackImpressionResponse) Reset() {
	*x = TrackImpressionResponse{}
	mi := &file_impression_tracking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackImpressionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackImpressionResponse) ProtoMessage() {}

func (x *TrackImpressionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_impression_tracking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackImpressionResponse.ProtoReflect.Descriptor instead.
func (*TrackImpressionResponse) Descriptor() ([]byte, []int) {
	return file_impression_tracking_proto_rawDescGZIP(), []int{1}
}

func (x *TrackImpressionResponse) GetAdId() string {
	if x != nil {
		return x.AdId
	}
	return ""
}

func (x *TrackImpressionResponse) GetTotalImpressions() int64 {
	if x != nil {
		return x.TotalImpressions
	}
	return 0
}

var File_impression_tracking_proto protoreflect.FileDescriptor

const file_impression_tracking_proto_rawDesc = "" +
	"\n" +
	"\x19impression_tracking.proto\x12\x05arago\"-\n" +
	"\x16TrackImpressionRequest\x12\x13\n" +
	"\x05ad_id\x18\x01 \x01(\tR\x04adId\"[\n" +
	"\x17TrackImpressionResponse\x12\x13\n" +
	"\x05ad_id\x18\x01 \x01(\tR\x04adId\x12+\n" +
	"\x11total_impressions\x18\x02 \x01(\x03R\x10totalImpressions2l\n" +
	"\x18ImpressionTrackerService\x12P\n" +
	"\x0fTrackImpression\x12\x1d.arago.TrackImpressionRequest\x1a\x1e.arago.TrackImpressionResponseB-Z+github.com/Baglyy/impression_tracking/protob\x06proto3"

var (
	file_impression_tracking_proto_rawDescOnce sync.Once
	file_impression_tracking_proto_rawDescData []byte
)

func file_impression_tracking_proto_rawDescGZIP() []byte {
	file_impression_tracking_proto_rawDescOnce.Do(func() {
		file_impression_tracking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_impression_tracking_proto_rawDesc), len(file_impression_tracking_proto_rawDesc)))
	})
	return file_impression_tracking_proto_rawDescData
}

var file_impression_tracking_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_impression_tracking_proto_goTypes = []any{
	(*TrackImpressionRequest)(nil),  // 0: arago.TrackImpressionRequest
	(*TrackImpressionResponse)(nil), // 1: arago.TrackImpressionResponse
}
var file_impression_tracking_proto_depIdxs = []int32{
	0, // 0: arago.ImpressionTrackerService.TrackImpression:input_type -> arago.TrackImpressionRequest
	1, // 1: arago.ImpressionTrackerService.TrackImpression:output_type -> arago.TrackImpressionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_impression_tracking_proto_init() }
func file_impression_tracking_proto_init() {
	if File_impression_tracking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_impression_tracking_proto_rawDesc), len(file_impression_tracking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_impression_tracking_proto_goTypes,
		DependencyIndexes: file_impression_tracking_proto_depIdxs,
		MessageInfos:      file_impression_tracking_proto_msgTypes,
	}.Build()
	File_impression_tracking_proto = out.File
	file_impression_tracking_proto_goTypes = nil
	file_impression_tracking_proto_depIdxs = nil
}
